### ISSUE TITLE
Removing wire not working as expected

### ISSUE THREAD

**Issue by mattlazarowitz** [yadomi/node-red-contrib-philipshue-events#18] opened 2022-10-18 20:47 UTC
After deleting my wire connecting a debug node to a phillipshue-event node, the debug node will continue to receive messages from the hue node. Other nodes I've tried are working as expected, it's just the phillipshue-event node that seems to be affected. I have to delete the receiving node for it to stop receiving messages.

**Comment by andesse** [comment] 2022-10-18 20:59
@mattlazarowitz did you forget to deploy after removing the connection?

I don't think that has something to do with yadomis node.

**Comment by mattlazarowitz** [comment] 2022-10-18 22:34
Yes, I re-dployed. I had also tried reloading the web page. 
However, after returning to the interface to try to get a reproduction on camera, the issue is no longer reproducible. 
I don't see anything in my logs to help pinpoint what might have been the issue either. 
It looks like this is probably an annoying but rare and difficult to reproduce issue so you can probably close this.

**Comment by yadomi** [comment] 2022-10-28 18:58
Hello, @mattlazarowitz thank for the issue. However, as @andesse said, I don't think the issue is related to this node. Wires, connections and such are handled at the node-RED code level. 

I'm closing the issue, feel free to open another one if you have more details about the issue.

**Closed as completed by yadomi** 2022-10-28 18:58 UTC
